// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/rcarvalho-pb/payment_project-go/internal/domain/invoice"
import "github.com/rcarvalho-pb/payment_project-go/internal/views/components"

func Layout(invoices []*invoice.Invoice, metrics components.ChartData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"pt-br\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Gopher Dashboard - Templ + HTMX</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script><style>\n        #log-container {\n            height: 200px;\n            overflow-y: auto;\n            font-family: monospace;\n            font-size: 0.85rem;\n        }\n\n        .log-entry {\n            border-bottom: 1px solid #333;\n            padding: 2px 0;\n        }\n    </style></head><body class=\"bg-light\"><nav class=\"navbar navbar-dark bg-dark mb-4\"><div class=\"container\"><span class=\"navbar-brand\">Gopher Control Panel</span></div></nav><div class=\"container\"><div class=\"row g-4\"><div class=\"col-md-8\"><div class=\"card shadow-sm mb-4\"><div class=\"card-body\"><h5 class=\"card-title\">Novo Elemento</h5><form hx-post=\"/invoices\" hx-target=\"#table-body\" hx-swap=\"afterbegin\" class=\"row g-3\"><div class=\"col-md-4\"><input type=\"text\" name=\"id\" class=\"form-control\" placeholder=\"ID\" required></div><div class=\"col-md-6\"><input type=\"number\" name=\"amount\" class=\"form-control\" placeholder=\"Valor\" required></div><div class=\"col-md-2\"><button type=\"submit\" class=\"btn btn-success w-100\">Criar</button></div></form></div></div><div class=\"card shadow-sm\"><div class=\"table-responsive\"><table class=\"table table-hover align-middle mb-0\"><thead class=\"table-light\"><tr><th>ID</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead> <tbody id=\"table-body\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, inv := range invoices {
			templ_7745c5c3_Err = components.InvoiceRow(inv).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</tbody></table></div></div></div><div class=\"col-md-4\"><div class=\"card shadow-sm mb-4\"><div class=\"card-body\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.MetricsDashboard(metrics).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></div></div></div><div id=\"modal-container\"></div><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><script src=\"https://unpkg.com/htmx.org/dist/ext/sse.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
